---

- hosts: all
  sudo: yes
  vars:
    citadel_bucket: 'balanced-citadel'

  vars_files:
    - defaults/main.yml

  roles:
    - supervisord
    - joshualund.ruby-common
    - joshualund.ruby-1_9_3

  handlers:
    - include: handlers/main.yml

  tasks:
    - name: install berkshelf api
      sudo: yes
      include: tasks/main.yml
      tags: berkshelf
