---

- name: create berkshelf group
  group: name={{ berkshelf_api_group }} state=present

- name: create berkshelf user
  user: >
    name={{ berkshelf_api_owner }}
    group={{ berkshelf_api_group }}
    password=no
    system=yes
    home={{ berkshelf_api_home }}
    state=present

- name: dirs
  file: >
    path={{ item }}
    owner={{ berkshelf_api_owner }}
    group={{ berkshelf_api_group }}
    state=directory
    mode=0755
  with_items:
  - /var/run/berkshelf
  - /var/log/berkshelf
  - /var/lib/berkshelf
  - "{{ berkshelf_api_home }}"
  - /etc/berkshelf
  notify: restart berkshelf