---
# handlers file for ansible-berkshelf-api
- name: start berkshelf
  supervisorctl: name=berkshelf-api state=present

- name: restart berkshelf
  supervisorctl: name=berkshelf-api state=restarted

- name: restart nginx
  service: name=nginx state=restarted
